### ISSUE TITLE
Analyze the Common Crawl data

### ISSUE THREAD

**Issue by vinitshahdeo** [postman-open-technologies/openapi-web-search#2]
Analyze a [Common Crawl](https://commoncrawl.org/) `index` file *(not the full data)* to identify subdomains, paths, and filenames that are API-related and may contain [OpenAPI definitions](https://spec.openapis.org/oas/latest.html#definitions).

Share your **approach** and **findings** after the analysis of the common crawl.

> **Note**: This is a qualifying task for **[GSoC'23](https://blog.postman.com/join-postman-at-google-summer-of-code-2023/).** Refer to [`CONTRIBUTOR_GUIDANCE.md`](https://github.com/postman-open-technologies/gsoc-2023/blob/main/CONTRIBUTOR_GUIDANCE.md)

**Comment by ankit-pn** [comment]
Hi Vinit,

Thank you for the qualification task. I have analyzed a portion of the Common Crawl URL index file on my local machine. Although the entire dataset is quite large (around 254 GB), I focused on a smaller subset that is approximately 4 GB in size. This subset is in the form of raw, unformatted text.

I wrote a Python script to filter out the essential data that we require and convert it into a readable JSON format. I then searched this database using keywords such as "openapi," "swagger," "swagger.yaml," and "openapi.yaml."

Here are some screenshots of my search results. If you would like me to submit my Python script, I am happy to do so.
![Screenshot from 2023-03-21 10-37-21](https://user-images.githubusercontent.com/61223051/226525241-5dd2815c-5fa1-4c98-ae75-5a6aee09e598.png)
![Screenshot from 2023-03-21 10-36-49](https://user-images.githubusercontent.com/61223051/226525251-f2de0b60-4cd8-4dc4-9437-d7f3b83ede2f.png)
![Screenshot from 2023-03-21 10-36-33](https://user-images.githubusercontent.com/61223051/226525254-5f1cbaad-cb76-45be-a6d9-f4c9f7edc1d5.png)
![Screenshot from 2023-03-21 10-32-56](https://user-images.githubusercontent.com/61223051/226525256-3ff20cfb-d579-45a3-a7f6-da24b6669e89.png)

**Comment by ankit-pn** [comment]
Imo, Searching for keywords like openapi.json, swagger.json, openapi.yaml and swagger.yaml in URL will make more sense if we are searching for those files

**Comment by saip007** [comment]
Hi @ankit-pn Can you help me in downloading the index file!!.

**Comment by priyanshu-kun** [comment]
> Hi @ankit-pn Can you help me in downloading the index file!!.

If I'm not mistaken you can begin your search from here https://commoncrawl.org/the-data/get-started/. Choose the dataset you like and find the index file there. To access the data, I would suggest reading this https://commoncrawl.org/access-the-data/ article.

**Comment by priyanshu-kun** [comment]
> > Hi @ankit-pn Can you help me in downloading the index file!!.
> 
> If I'm not mistaken you can begin your search from here https://commoncrawl.org/the-data/get-started/. Choose the dataset you like and find the index file there. To access the data, I would suggest reading this https://commoncrawl.org/access-the-data/ article.

**Comment by priyanshu-kun** [comment]
or better you can find all index files from this https://index.commoncrawl.org/ website!

**Comment by ankit-pn** [comment]
> Hi @ankit-pn Can you help me in downloading the index file!!.

Do as what priyanshu said and you will be good to go.😅

**Comment by saip007** [comment]
thankyou both @priyanshu-kun @ankit-pn

**Comment by priyanshu-kun** [comment]
> > Hi @ankit-pn Can you help me in downloading the index file!!.
> 
> Do as what priyanshu said and you will be good to go.sweat_smile

Did I say something inappropriate? I don't know or is it just my misinterpretation?

**Comment by ankit-pn** [comment]
> > > Hi @ankit-pn Can you help me in downloading the index file!!.
> > 
> > Do as what priyanshu said and you will be good to go.sweat_smile
> 
> Did I say something inappropriate? I don't know or is it just my misinterpretation?

No nothing.

**Comment by destrex271** [comment]
Hey everyone!
Just started out with my research and for today I read about the topics as given above. I tried two approaches today. 

First I started out by going through the index file for CC-MAIN-2022-05 archive and secondly I used the [cdx server api client](https://github.com/ikreymer/cdx-index-client). For querying the required data for now I tried wildcards according to s[wagger documentaion](https://swagger.io/docs/specification/api-host-and-base-path/) on OpenAPI 3 and 2 but this part requires a little more work. As far as the two approaches go in the first one i.e downloading the index file I realised that in the proposed project the archive index files required would be very large and since these files get updated in an interval of one or two months updating such a large dataset would be a hassle(i can be wrong about this but I though that this could be one of the problems that we might face). 

One of the solutions for the same can be to use a custom cdx server client (as the one that I used was a little buggy) but this would cost us a lot of time as I encountered a lot of time out errors when using this approach. 
For now I will be testing out querying the [Columnar Format](https://commoncrawl.org/2018/03/index-to-warc-files-and-urls-in-columnar-format/) which the folks at common crawl have suggested if we just want to query urls from the index. We can try to formulate a solution around this. I'll try to present my findings in the form of a demo asap.

**Comment by priyanshu-kun** [comment]
@vinitshahdeo  do we have to find documentation and repos for those openAPI definations in the common crawl index dataset?

**Comment by HimanshuS129** [comment]
> 

@priyanshu-kun We need to index valid API Definitions. Even if you find documentations or repos how would you validate them?

**Comment by priyanshu-kun** [comment]
> 

There are npm packages out there like swagger-parser or you can google it.

**Comment by Prajwalprakash3722** [comment]
Hey @vinitshahdeo, here was my experience 

I started by setting up a list of API-related keywords, and then used the `gzip` library to read the Common Crawl index file. For each URL in the file, checked if it matched the pattern of an API-related URL, and if so, extracted the subdomain, path, and filename from the URL.

Then made a request to the URL using the `requests` library and checked the response body for any of the API-related keywords. If a match was found then pushed the URL to a list of matched URLs and logged relevant information indicating which keyword was found and where it was found in the URL.

After all the URLs had been checked, saved the list of matched URLs to a JSON file

### Ultimate multitask-er
It was taking forever to loop through all the data and doing all above operations, As a computer science student I am not used to slow things at all, so remembered threading concept from `Operating System` immedaitly rewrote the code (threading to download and process the response bodies from multiple URLs in parallel) , saw a considerable improvement in processing time.

### Fun Fact
- It's interesting how the term "swagger" has different meanings in different contexts.
- There is an online shop called [`swagger`](http://shop.swagger.kr/index.html) in Korea that sells streetwear and accessories. 🤣
